version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install numpy
      - pip install PyWavelets ptwt
      - pip install asciitree==0.3.2
      - pip install .  # 不用 .[doc]，因为你没定义这个 extra
      - pip install torch open3d dask tifffile scikit-image h5py pandas opencv-python matplotlib natsort
      - pip install sphinx-rtd-theme nbsphinx sphinx-copybutton sphinxcontrib-video sphinx-togglebutton

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
