# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04       # Read the Docs 构建环境版本
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py  # 指定 Sphinx 配置文件路径

python:
  install:
    - requirements: docs/requirements.txt
