version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install numpy
      - pip install pywt ptwt
      - pip install .[doc]
      - pip install torch open3d dask tifffile skimage h5py pandas cv2 matplotlib natsort
      - pip install sphinx-rtd-theme nbsphinx sphinx-copybutton sphinxcontrib-video sphinx-togglebutton

sphinx:
  configuration: docs/conf.py
